### ISSUE TITLE
Warning: URI.escape is obsolete

### ISSUE THREAD

**Issue by cdhagmann** [local-ch/lhc#193]
In Ruby 2.7, URI.escape now shows a warning and in Ruby 3.0 it would not run.

lhc-13.1.0/lib/lhc/request.rb:94: warning: URI.escape is obsolete

**Comment by marcoroth** [comment]
Hey @cdhagmann,

I think this has already been addressed in [this commit](https://github.com/local-ch/lhc/commit/bddf5a9d4a252b5057775ee865f00354d64ca391#diff-2834f6f63cc4e8c04e734a8e903d04bd8dd2fe918dd6ffc8fd7bedf69a4ded65R94).

But there was no release since then. I guess it just needs a release ☺️

**Comment by marcoroth** [comment]
But you can do this as a workaround in the meantime:

```ruby
gem 'lhc', git: 'https://github.com/local-ch/lhc'
```

**Comment by dimameshcharakou** [comment]
Thanks for the reporting! Should be fixed now: https://github.com/local-ch/lhc/pull/194
